FROM openjdk:11
LABEL maintainer="kirtishkhandar"
ADD target/packaging-and-delivery-module-0.0.1-SNAPSHOT.jar packaging-and-delivery-module.jar
ENTRYPOINT ["java", "-jar", "packaging-and-delivery-module.jar"]